
[blockentity]
	teblacklist = []
	autoBlacklistErroredTEs = true
	blockblacklist = ["minecraft:bedrock"]

[biomes]
	customBiomeMappings = []
	resetAllTerrain = false

[client]
	mouseFloodCtrl = 100

[explosions]
	minBlastEffect = 0.25
	explosionRate = [2000, 10000]
	affectAir = true
	explosionRadius = 127

[misc]
	debug = true

