#With this you can't see portal-in-portal
compatibility_render_mode = false
#With this the performance may drop
check_gl_error = false
#Max Portal-in-portal Render Layer
#Range: 1 ~ 10
max_portal_layer = 5
#Render Yourself In Portal
render_yourself_in_portal = true
#This May Decrease FPS
correct_cross_portal_entity_rendering = true
#See the Wiki to Know How to Configure it
dimension_render_redirect = "immersive_portals:alternate1->minecraft:overworld\nimmersive_portals:alternate2->minecraft:overworld\nimmersive_portals:alternate3->minecraft:overworld\nimmersive_portals:alternate4->minecraft:overworld\nimmersive_portals:alternate5->minecraft:overworld\n"

