
[General]
	#Use items to change the type of a bee.
	#If false, productive bees can only be obtained through breeding.
	enableItemConverting = true
	#How often should a bee attempt to generate items while in the hive.
	itemTickRate = 500

[Bees]

	#Bee production rates.
	[Bees.itemProductionRates]
		"productivebees:slimy_bee" = 0.3
		"productivebees:glowing_bee" = 0.25
		"productivebees:gold_bee" = 0.1
		"productivebees:draconic_bee" = 0.01
		"productivebees:dye_bee" = 0.5
		"productivebees:wither_bee" = 0.01
		"productivebees:blazing_bee" = 0.15
		"productivebees:emerald_bee" = 0.05
		"productivebees:iron_bee" = 0.1
		"productivebees:skeletal_bee" = 0.1
		"productivebees:redstone_bee" = 0.25
		"productivebees:ender_bee" = 0.05
		"productivebees:zombie_bee" = 0.1
		"productivebees:diamond_bee" = 0.1
		"productivebees:creeper_bee" = 0.1
		"productivebees:magmatic_bee" = 0.2
		"minecraft:bee" = 0.25
		"productivebees:lapis_bee" = 0.2
		"productivebees:quartz_bee" = 0.25

